version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: MySqlServer_Automacao
    restart: always
    ports:
            - "3306:3306"
    volumes:
      - /home/cpd/Dropbox/Automacao/bancoDados/:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=automacaoDB
    networks:
      - network

  php-fpm:
    image: bitnami/php-fpm:latest
    container_name: PhpFpmServer_Automacao
    restart: always
    volumes:
      - /home/cpd/Dropbox/Automacao/app:/usr/share/nginx/html/
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: PhpMyAdmin_Automacao
    restart: always
    ports:
      - 8181:80
    environment:
      - MYSQL_USERNAME=admin
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_ARBITRARY=1
    networks:
      - network

  ngnix:
    image: nginx:latest
    container_name: NginxServer_Automacao
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/cpd/Dropbox/Automacao/app/:/usr/share/nginx/html/
#      - ./defaultNginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

networks:
  network:
    driver: bridge
