version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysqlserver_Automacao
    restart: always
    ports:
            - "3306:3306"
    volumes:
      - /home/cpd/Dropbox/Automacao/bancoDados/:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=automacaoDB
      - MYSQL_USER=sergio
      - MYSQL_PASSWORD=sergio@
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_Automacao
    restart: always
    ports:
      - 8181:80
    environment:
      - MYSQL_USERNAME=admin
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_ARBITRARY=1
    links:
      - mysql
    networks:
      - network

  tomcat:
    image: tomcat:latest
    container_name: tomcat_Automacao
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/cpd/Dropbox/Automacao/app:/usr/local/tomcat/webapps
    networks:
      - network

#  ngnix:
#    image: nginx:latest
#    container_name: NginxServer
#    restart: always
#    ports:
#      - 80:80
#    volumes:
#      - /home/cpd/Dropbox/Automacao/app/:/usr/share/nginx/html/
##      - ./defaultNginx.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - tomcat
#    networks:
#      - network

networks:
  network:
    driver: bridge
